// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

void* winrt_make_PowerToys_GPOWrapper_GPOWrapper()
{
    return winrt::detach_abi(winrt::make<winrt::PowerToys::GPOWrapper::factory_implementation::GPOWrapper>());
}
WINRT_EXPORT namespace winrt::PowerToys::GPOWrapper
{
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredAlwaysOnTopEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredAlwaysOnTopEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredAwakeEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredAwakeEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredCmdNotFoundEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredCmdNotFoundEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredColorPickerEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredColorPickerEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredCropAndLockEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredCropAndLockEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredFancyZonesEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredFancyZonesEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredFileLocksmithEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredFileLocksmithEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredSvgPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredSvgPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMarkdownPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMarkdownPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMonacoPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMonacoPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredPdfPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredPdfPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredGcodePreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredGcodePreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredSvgThumbnailsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredSvgThumbnailsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredPdfThumbnailsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredPdfThumbnailsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredGcodeThumbnailsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredGcodeThumbnailsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredStlThumbnailsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredStlThumbnailsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredHostsFileEditorEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredHostsFileEditorEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredImageResizerEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredImageResizerEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredKeyboardManagerEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredKeyboardManagerEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredFindMyMouseEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredFindMyMouseEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMouseHighlighterEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMouseHighlighterEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMouseJumpEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMouseJumpEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMousePointerCrosshairsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMousePointerCrosshairsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMouseWithoutBordersEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMouseWithoutBordersEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredPowerRenameEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredPowerRenameEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredPowerLauncherEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredPowerLauncherEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredQuickAccentEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredQuickAccentEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredRegistryPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredRegistryPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredScreenRulerEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredScreenRulerEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredShortcutGuideEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredShortcutGuideEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredTextExtractorEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredTextExtractorEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredAdvancedPasteEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredAdvancedPasteEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredVideoConferenceMuteEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredVideoConferenceMuteEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredPeekEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredPeekEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetDisableNewUpdateToastValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetDisableNewUpdateToastValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetDisableAutomaticUpdateDownloadValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetDisableAutomaticUpdateDownloadValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetDisableShowWhatsNewAfterUpdatesValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetDisableShowWhatsNewAfterUpdatesValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetAllowExperimentationValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetAllowExperimentationValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetRunPluginEnabledValue(param::hstring const& pluginID)
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetRunPluginEnabledValue(pluginID);
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredEnvironmentVariablesEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredEnvironmentVariablesEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredQoiPreviewEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredQoiPreviewEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredQoiThumbnailsEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredQoiThumbnailsEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetAllowedAdvancedPasteOnlineAIModelsValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetAllowedAdvancedPasteOnlineAIModelsValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbClipboardSharingEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbClipboardSharingEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbFileTransferEnabledValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbFileTransferEnabledValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbUseOriginalUserInterfaceValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbUseOriginalUserInterfaceValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbDisallowBlockingScreensaverValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbDisallowBlockingScreensaverValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbSameSubnetOnlyValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbSameSubnetOnlyValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbValidateRemoteIpValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbValidateRemoteIpValue();
    }
    winrt::PowerToys::GPOWrapper::GpoRuleConfigured GPOWrapper::GetConfiguredMwbDisableUserDefinedIpMappingRulesValue()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbDisableUserDefinedIpMappingRulesValue();
    }
    hstring GPOWrapper::GetConfiguredMwbPolicyDefinedIpMappingRules()
    {
        return PowerToys::GPOWrapper::implementation::GPOWrapper::GetConfiguredMwbPolicyDefinedIpMappingRules();
    }
}
