// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#include "winrt/BackgroundActivator.h"
namespace winrt::BackgroundActivator::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES BackgroundHandler_base : implements<D, BackgroundActivator::BackgroundHandler, I...>
    {
        using base_type = BackgroundHandler_base;
        using class_type = BackgroundActivator::BackgroundHandler;
        using implements_type = typename BackgroundHandler_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"BackgroundActivator.BackgroundHandler";
        }
    };
}
namespace winrt::BackgroundActivator::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES BackgroundHandlerT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = BackgroundActivator::BackgroundHandler;

        hstring GetRuntimeClassName() const
        {
            return L"BackgroundActivator.BackgroundHandler";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_BACKGROUNDHANDLER_XAML_G_H) || __has_include("BackgroundHandler.xaml.g.h")

#include "BackgroundHandler.xaml.g.h"

#else

namespace winrt::BackgroundActivator::implementation
{
    template <typename D, typename... I>
    using BackgroundHandlerT = BackgroundHandler_base<D, I...>;
}

#endif
