// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

void* winrt_make_BackgroundActivator_BackgroundHandler()
{
    return winrt::detach_abi(winrt::make<winrt::BackgroundActivator::factory_implementation::BackgroundHandler>());
}
WINRT_EXPORT namespace winrt::BackgroundActivator
{
    BackgroundHandler::BackgroundHandler() :
        BackgroundHandler(make<BackgroundActivator::implementation::BackgroundHandler>())
    {
    }
}
