// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_PowerToys_GPOWrapper_1_H
#define WINRT_PowerToys_GPOWrapper_1_H
#include "winrt/impl/PowerToys.GPOWrapper.0.h"
WINRT_EXPORT namespace winrt::PowerToys::GPOWrapper
{
    struct WINRT_IMPL_EMPTY_BASES IGPOWrapper :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGPOWrapper>
    {
        IGPOWrapper(std::nullptr_t = nullptr) noexcept {}
        IGPOWrapper(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGPOWrapperStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGPOWrapperStatics>
    {
        IGPOWrapperStatics(std::nullptr_t = nullptr) noexcept {}
        IGPOWrapperStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
