#pragma once
#include "GPOWrapper.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::PowerToys::GPOWrapper::implementation
{
    struct GPOWrapper : GPOWrapperT<GPOWrapper>
    {
        GPOWrapper() = default;

        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredAlwaysOnTopEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredAwakeEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredCmdNotFoundEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredColorPickerEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredCropAndLockEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredFancyZonesEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredFileLocksmithEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredSvgPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMarkdownPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMonacoPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredPdfPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredGcodePreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredSvgThumbnailsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredPdfThumbnailsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredGcodeThumbnailsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredStlThumbnailsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredHostsFileEditorEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredImageResizerEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredKeyboardManagerEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredFindMyMouseEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMouseHighlighterEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMouseJumpEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMousePointerCrosshairsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMouseWithoutBordersEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredPowerRenameEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredPowerLauncherEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredQuickAccentEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredRegistryPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredScreenRulerEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredShortcutGuideEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredTextExtractorEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredAdvancedPasteEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredVideoConferenceMuteEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredPeekEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetDisableNewUpdateToastValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetDisableAutomaticUpdateDownloadValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetDisableShowWhatsNewAfterUpdatesValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetAllowExperimentationValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetRunPluginEnabledValue(hstring const& pluginID);
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredEnvironmentVariablesEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredQoiPreviewEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredQoiThumbnailsEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetAllowedAdvancedPasteOnlineAIModelsValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbClipboardSharingEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbFileTransferEnabledValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbUseOriginalUserInterfaceValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbDisallowBlockingScreensaverValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbSameSubnetOnlyValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbValidateRemoteIpValue();
        static winrt::PowerToys::GPOWrapper::GpoRuleConfigured GetConfiguredMwbDisableUserDefinedIpMappingRulesValue();
        static hstring GetConfiguredMwbPolicyDefinedIpMappingRules();
    };
}
namespace winrt::PowerToys::GPOWrapper::factory_implementation
{
    struct GPOWrapper : GPOWrapperT<GPOWrapper, implementation::GPOWrapper>
    {
    };
}
