// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_BackgroundActivator_1_H
#define WINRT_BackgroundActivator_1_H
#include "winrt/impl/BackgroundActivator.0.h"
WINRT_EXPORT namespace winrt::BackgroundActivator
{
    struct WINRT_IMPL_EMPTY_BASES IBackgroundHandler :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBackgroundHandler>
    {
        IBackgroundHandler(std::nullptr_t = nullptr) noexcept {}
        IBackgroundHandler(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
