// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240111.5

#pragma once
#ifndef WINRT_BackgroundActivator_2_H
#define WINRT_BackgroundActivator_2_H
#include "winrt/impl/BackgroundActivator.1.h"
WINRT_EXPORT namespace winrt::BackgroundActivator
{
    struct WINRT_IMPL_EMPTY_BASES BackgroundHandler : winrt::BackgroundActivator::IBackgroundHandler
    {
        BackgroundHandler(std::nullptr_t) noexcept {}
        BackgroundHandler(void* ptr, take_ownership_from_abi_t) noexcept : winrt::BackgroundActivator::IBackgroundHandler(ptr, take_ownership_from_abi) {}
        BackgroundHandler();
    };
}
#endif
