// This file was auto-generated. Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by runner.rc

//////////////////////////////
// Non-localizable

#define FILE_DESCRIPTION "PowerToys.Runner"
#define INTERNAL_NAME "PowerToys"
#define ORIGINAL_FILENAME "PowerToys.exe"

// Non-localizable
//////////////////////////////

#define APPICON 101
#define ID_TRAY_MENU 102

#define ID_EXIT_MENU_COMMAND 40001
#define ID_SETTINGS_MENU_COMMAND 40002
#define ID_ABOUT_MENU_COMMAND 40003
#define ID_REPORT_BUG_COMMAND 40004
#define ID_DOCUMENTATION_MENU_COMMAND 40005
#define ID_QUICK_ACCESS_MENU_COMMAND 40006
#define IDS_ERROR 101
#define IDS_COULDNOT_RESTART_NONELEVATED 102
#define IDS_COULDNOT_RESTART_ELEVATED 103
#define IDS_ANOTHER_INSTANCE_RUNNING 104
#define IDS_AUTOUPDATE_SUCCESS 105
#define IDS_MSI_VERSION_IS_ALREADY_RUNNING 106
#define IDS_DOWNLOAD_UPDATE_ERROR 107
#define IDS_OLDER_MSIX_UNINSTALLED 108
#define IDS_PT_UPDATE_MESSAGE_BOX_TEXT 109
#define IDS_STARTUP_DISABLED_BY_POLICY 110
#define IDS_STARTUP_DISABLED_BY_USER 111
#define IDS_GITHUB_NEW_VERSION_AVAILABLE 112
#define IDS_GITHUB_NEW_VERSION_UPDATE_NOW 113
#define IDS_GITHUB_NEW_VERSION_AVAILABLE_OFFER_VISIT 114
#define IDS_GITHUB_NEW_VERSION_MORE_INFO 115
#define IDS_TOAST_TITLE 116
#define IDS_QUICK_ACCESS_MENU_TEXT 117
#define IDS_SETTINGS_MENU_TEXT 118
#define IDS_DOCUMENTATION_MENU_TEXT 119
#define IDS_EXIT_MENU_TEXT 120
#define IDS_SUBMIT_BUG_TEXT 121
#define IDS_BUGREPORT_SUCCESS 122
#define IDS_PT_VERSION_CHANGE_ASK_FOR_COMPUTER_RESTART 123
#define IDS_TRAY_ICON_ADMIN_TOOLTIP 124
